<?php
/**
 * Dc_MercadoPagoPlus
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Dc
 * @package    Dc_MercadoPagoPlus
 * @copyright  Copyright (c) 2014-2015 Damián Culotta. (http://www.damianculotta.com.ar/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<p><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></p>
<?php if ($this->getButtonLink()): ?>
<table>
    <tbody>
        <?php if ($this->getInstructions()): ?>
        <tr>
            <td><?php echo $this->getInstructions(); ?></td>
        </tr>
        <?php endif; ?>
        <tr>
            <td><?php echo $this->getButtonLink(); ?></td>
        </tr>
    </tbody>
</table>
<?php endif; ?>
