<?php
/**
 * Dc_MercadoPagoPlus
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Dc
 * @package    Dc_MercadoPagoPlus
 * @copyright  Copyright (c) 2014-2015 Damián Culotta. (http://www.damianculotta.com.ar/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<p><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></p>
<?php if ($this->getButtonLink()): ?>
<table>
    <tbody>
        <?php if ($this->getInstructions()): ?>
        <tr>
            <td><?php echo $this->getInstructions(); ?></td>
        </tr>
        <?php endif; ?>
        <tr>
            <td style="padding:15px 0px 10px 0px"><a href="<?php echo $this->getButtonLink(); ?>" target="_blank" style="color: #FFF;font-size: 14px;line-height: 1em;padding: .8em 1.5em;font-family: Arial,serif;font-weight: normal;background-color: #36a1f1;background-image: -webkit-gradient(linear,left top,left bottom,color-stop(0%,#36a1f1),color-stop(100%,#0f79c9));background-image: -webkit-linear-gradient(#36a1f1,#0f79c9);background-image: -moz-linear-gradient(#36a1f1,#0f79c9);background-image: -o-linear-gradient(#36a1f1,#0f79c9);background-image: linear-gradient(#36a1f1,#0f79c9);-webkit-box-shadow: inset 0 1px #97dcff;box-shadow: 0 1px #97dcff inset;color: #fff;border: 1px solid #0d6fb9;border-radius: 4px 4px 4px 4px;cursor: pointer;text-decoration: none;"><?php echo $this->__('Pay with MercadoPago'); ?></a></td>
        </tr>
    </tbody>
</table>
<?php endif; ?>
